version: 0.0.{build}
image:
- macos-bigsur
- Visual Studio 2022

configuration:
  - Release

build:
  parallel: true  

for:
  -
    matrix:
      only:
        - image: macos-bigsur

    before_build:
      - cmake . -G Xcode -B .build

    build_script:
      - cmake --build .build --config Release -j

  -
    matrix:
      only:
        - image: Visual Studio 2022
    before_build:
      - cmake . -G "Visual Studio 17 2022" -B .build

    build_script:
      - cmake --build .build --config Release -j
