$input v_view, v_position, v_bc, v_normal, v_texcoord0, v_color0, v_tangent, v_bitangent

#include "../definitions.sh"
#include "../common/common.sh"
#include "../uniforms.sh"

SAMPLER2D(SAMPLER2D_DIFFUSE, SAMPLER2D_DIFFUSE_STAGE);
SAMPLER2D(SAMPLER2D_NORMALS, SAMPLER2D_NORMALS_STAGE);
SAMPLER2D(SAMPLER2D_ALBEDO, SAMPLER2D_ALBEDO_STAGE);
SAMPLER2D(SAMPLER2D_ROUGH_METALLIC, SAMPLER2D_ROUGH_METALLIC_STAGE);
SAMPLER2D(SAMPLER2D_AO, SAMPLER2D_AO_STAGE);
SAMPLER2D(SAMPLER2D_EMISSIVE, SAMPLER2D_EMISSIVE_STAGE);
SAMPLER2D(SAMPLER2D_OPACITY, SAMPLER2D_OPACITY_STAGE);

void main()
{
    vec4 color = texture2D(SAMPLER2D_DIFFUSE, vec2(v_texcoord0.x, 1.0 - v_texcoord0.y));
    gl_FragColor = color;
}